"""Add img_url to menuitems

Revision ID: 143ec5027e3a
Revises: aae5743d66e0
Create Date: 2023-04-20 09:41:05.281706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '143ec5027e3a'
down_revision = 'aae5743d66e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menuitems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menuitems', schema=None) as batch_op:
        batch_op.drop_column('img_url')

    # ### end Alembic commands ###
