"""Delete orderitem id column from Receipt

Revision ID: 398e49b5dcfd
Revises: 4161c9f6a46d
Create Date: 2023-04-17 16:09:39.696515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '398e49b5dcfd'
down_revision = '4161c9f6a46d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_receipts_orderitem_id_orderitems', type_='foreignkey')
        batch_op.drop_column('orderitem_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orderitem_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('fk_receipts_orderitem_id_orderitems', 'orderitems', ['orderitem_id'], ['id'])

    # ### end Alembic commands ###
