"""Add relationship between orderitems and receipts tables

Revision ID: 4161c9f6a46d
Revises: 4ff52a488fbf
Create Date: 2023-04-17 15:22:44.692102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4161c9f6a46d'
down_revision = '4ff52a488fbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orderitems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receipt_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_orderitems_receipt_id_receipts'), 'receipts', ['receipt_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orderitems', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_orderitems_receipt_id_receipts'), type_='foreignkey')
        batch_op.drop_column('receipt_id')

    # ### end Alembic commands ###
