"""Add cascade to foreign keys

Revision ID: 78c9b23af0a8
Revises: f7576e476418
Create Date: 2023-04-24 17:29:14.455965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78c9b23af0a8'
down_revision = 'f7576e476418'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orderitems', schema=None) as batch_op:
        batch_op.drop_constraint('fk_orderitems_menuitem_id_menuitems', type_='foreignkey')
        batch_op.drop_constraint('fk_orderitems_receipt_id_receipts', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_orderitems_receipt_id_receipts'), 'receipts', ['receipt_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_orderitems_menuitem_id_menuitems'), 'menuitems', ['menuitem_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orderitems', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_orderitems_menuitem_id_menuitems'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_orderitems_receipt_id_receipts'), type_='foreignkey')
        batch_op.create_foreign_key('fk_orderitems_receipt_id_receipts', 'receipts', ['receipt_id'], ['id'])
        batch_op.create_foreign_key('fk_orderitems_menuitem_id_menuitems', 'menuitems', ['menuitem_id'], ['id'])

    # ### end Alembic commands ###
